In [1]:
import numpy as np

In [2]:
X = np.array([1.0, 0.5])

In [3]:
X.shape

(2,)

In [4]:
X


array([1. , 0.5])

In [5]:
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

In [6]:
W1.shape

(2, 3)

In [8]:
W1

array([[0.1, 0.3, 0.5],
       [0.2, 0.4, 0.6]])

In [9]:
a1 = np.dot(X, W1)

In [10]:
a1.shape

(3,)

In [11]:
a1

array([0.2, 0.5, 0.8])

In [12]:
1.0 * 0.1 + 0.5 * 0.2

0.2

In [13]:
b1 = np.array([0.1, 0.2, 0.3])

In [14]:
a1 = np.dot(X, W1) + b1

In [15]:
print(a1)

[0.3 0.7 1.1]


In [16]:
x1 = np.array([[1, 2 ], [3, 4]])
x2 = np.array([[5, 6 ], [7, 8]])

In [17]:
print(x1)

[[1 2]
 [3 4]]


In [18]:
print(x2)

[[5 6]
 [7 8]]


In [19]:
x1.shape

(2, 2)

In [20]:
x2.shape

(2, 2)

In [21]:
np.dot(x1, x2)

array([[19, 22],
       [43, 50]])

In [22]:
x1 = np.array([[1, 2 ]])
x2 = np.array([[5, 6 ], [7, 8]])

In [23]:
x1.shape

(1, 2)

In [24]:
x2.shape

(2, 2)

In [25]:
np.dot(x1, x2)

array([[19, 22]])