In [1]:
import numpy as np

In [3]:
a = np.array([0.3, 0.9, 5.0])

In [5]:
a = np.array([0.3, -0.9, 5.0])

In [6]:
a

array([ 0.3, -0.9,  5. ])

In [7]:
def softmax(a): 
  exp_a = np.exp(a)
  sum_exp_a = np.sum(exp_a) 
  y = exp_a / sum_exp_a 
  return y

In [8]:
y = softmax(a)

In [9]:
print(y)

[0.0089889 0.0027074 0.9883037]


In [10]:
np.sum(y)

1.0

Numerically stable Softmax

In [11]:
a = np.array([1010, 1000, 990])

In [12]:
y = softmax(a)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


In [13]:
print(y)

[nan nan nan]


In [14]:
def stable_softmax(a):
  c = np.max(a)
  exp_a = np.exp(a-c)
  sum_exp_a = sum(np.exp(a-c))
  y = exp_a/sum_exp_a
  return y

In [15]:
y = stable_softmax(a)

In [16]:
print(y)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


In [17]:
np.sum(y)

1.0